// Generated by CoffeeScript 1.4.0
(function() {

  Nimbus.Auth.setup("GDrive", "424243246254-n6b2v8j4j09723ktif41ln247n75pnts.apps.googleusercontent.com", "https://www.googleapis.com/auth/drive", "tweetdiary");

}).call(this);
